// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { getAppState } from '$lib/state.svelte';
  
  const appState = getAppState();

  const handleThemeChange = (newTheme: "auto" | "light" | "dark") => {
    appState.setTheme(newTheme);
  };
</script>

<div class="theme-toggle">
  <button title="auto theme" onclick={() => handleThemeChange('auto')} class:selected={appState.theme === 'auto'}>
    <div class="auto-icon"></div>
  </button>
  <button title="light theme" onclick={() => handleThemeChange('light')} class:selected={appState.theme === 'light'}>
    <div class="light-icon"></div>
  </button>
  <button title="dark theme" onclick={() => handleThemeChange('dark')} class:selected={appState.theme === 'dark'}>
    <div class="dark-icon"></div>
  </button>
</div>

// src/components/ThemeToggle.tsx
import React, { useContext } from "react";
import { ThemeContext } from "../context/ThemeContext";
import { Theme } from "../types";

const ThemeToggle: React.FC = () => {
  const { theme, setTheme } = useContext(ThemeContext)!;

  const handleThemeChange = (newTheme: Theme) => {
    setTheme(newTheme);
  };

  return (
    <div className="theme-toggle">
      <button
        title="System Theme"
        onClick={() => handleThemeChange("system")}
        className={`${theme === "system" ? "selected" : ""}`}
      >
        <div className="system-icon" />
      </button>
      <button
        title="Light Theme"
        onClick={() => handleThemeChange("light")}
        className={`${theme === "light" ? "selected" : ""}`}
      >
        <div className="light-icon" />
      </button>
      <button
        title="Dark Theme"
        onClick={() => handleThemeChange("dark")}
        className={`${theme === "dark" ? "selected" : ""}`}
      >
        <div className="dark-icon" />
      </button>
    </div>
  );
};
export default ThemeToggle;
