// src/components/CardGrid.tsx
import React, { useContext, useMemo } from "react";
import { motion } from "framer-motion";
import { SearchContext } from "../context/SearchContext";
import { Bookmark, Folder } from "../types";

const FolderCard: React.FC<{ folder: Folder }> = ({ folder }) => {
  const { setSelectedFolder } = useContext(SearchContext)!;

  const handleFolderClick = (folder: Folder) => {
    setSelectedFolder(folder.title);
  };

  return (
    <div key={folder.title} className="folder-card" onClick={() => handleFolderClick(folder)}>
      <span className="icon" />
      <h3 className="title">{folder.title}</h3>
    </div>
  );
};

const BookmarkCard: React.FC<{ bookmark: Bookmark }> = ({ bookmark }) => (
  <a key={bookmark.url} href={bookmark.url} target="_blank" rel="noopener noreferrer">
    <div className="bookmark-card">
      {!bookmark.icon && <span className="icon" />}
      {bookmark.icon && <img src={bookmark.icon} alt={bookmark.title} className="icon-image" />}

      <div className="info">
        <h3 className="title">{bookmark.title}</h3>
        <p className="url">{bookmark.url}</p>
      </div>

      {/* {bookmark.meta?.description && <p className="text-sm mt-2">{bookmark.meta.description}</p>} */}
    </div>
  </a>
);

const CardGrid: React.FC = () => {
  const { filteredBookmarks } = useContext(SearchContext)!;
  const folders = useMemo(() => filteredBookmarks.filter((item) => item.type === "folder"), [filteredBookmarks]);
  const bookmarks = useMemo(() => filteredBookmarks.filter((item) => item.type === "link"), [filteredBookmarks]);

  return (
    <motion.div className="card-grid" layout>
      {folders.length > 0 && (
        <div className="folder-grid">
          {folders.map((folder) => (
            <FolderCard folder={folder} />
          ))}
        </div>
      )}

      {folders.length > 0 && bookmarks.length > 0 && <hr className="divider"></hr>}

      {bookmarks.length > 0 && (
        <div className="bookmark-grid">
          {bookmarks.map((bookmark) => (
            <BookmarkCard bookmark={bookmark} />
          ))}
        </div>
      )}
    </motion.div>
  );
};

export default CardGrid;

// src/lib/components/CardGrid.svelte
<script lang="ts">
  import { getAppState } from '$lib/state.svelte';
  import type { Folder, Bookmark } from '$lib/types';

  const appState = getAppState();

  let folders = $derived(appState.filteredBookmarks.filter(item => item.type === 'folder') as Folder[]);
  let bookmarks = $derived(appState.filteredBookmarks.filter(item => item.type === 'link') as Bookmark[]);
</script>

<div class="card-grid">
  {#if folders.length > 0}
    <div class="folder-grid">
      {#each folders as folder (folder.id)}
        <a
          href="?folder={encodeURIComponent(folder.id)}"
          class="folder-card"
        >
          <span class="icon"></span>
          <h3 class="title">{folder.title}</h3>
        </a>
      {/each}
    </div>
  {/if}

  {#if folders.length > 0 && bookmarks.length > 0}
    <hr class="divider" />
  {/if}

  {#if bookmarks.length > 0}
    <div class="bookmark-grid">
      {#each bookmarks as bookmark (bookmark.url)}
        <a
          href={bookmark.url}
          target="_blank"
          rel="noopener noreferrer"
        >
          <div class="bookmark-card">
            {#if !bookmark.icon}
              <span class="icon"></span>
            {:else}
              <img src={bookmark.icon} alt={bookmark.title} class="icon-image" />
            {/if}
            <div class="info">
              <h3 class="title">{bookmark.title}</h3>
              <p class="url">{bookmark.url}</p>
            </div>
          </div>
        </a>
      {/each}
    </div>
  {/if}
</div>
