// src/components/FolderTree.tsx
import React, { useContext } from "react";
import { BookmarkContext } from "../context/BookmarkContext";
import { SearchContext } from "../context/SearchContext";
import { ThemeContext } from "../context/ThemeContext";
import { Folder } from "../types";

const FolderTree: React.FC = () => {
  const { bookmarks } = useContext(BookmarkContext)!;
  const { selectedFolder, setSelectedFolder } = useContext(SearchContext)!;
  const { hideSidebar } = useContext(ThemeContext)!;

  const handleFolderClick = (folder: Folder) => {
    setSelectedFolder(folder.title);
    hideSidebar();
  };

  const renderFolder = (folder: Folder) => (
    <li key={folder.title} className={`folder ${selectedFolder === folder.title ? "selected" : ""}`}>
      <div className="title" onClick={() => handleFolderClick(folder)}>
        <span className={`icon ${folder.icon ? "" : "default"}`}>{folder.icon}</span>
        <span className="folder-name">{folder.title}</span>
      </div>
      <ul>{folder.children.map((child) => child.type === "folder" && renderFolder(child))}</ul>
    </li>
  );

  return (
    <nav className="folder-tree">
      <ul>{bookmarks.map((item) => item.type === "folder" && renderFolder(item))}</ul>
    </nav>
  );
};

export default FolderTree;

// src/lib/components/FolderTree.svelte
<script lang="ts">
  import { getAppState } from '$lib/state.svelte';
  import type { Folder } from '$lib/types';

  const appState = getAppState();

  const handleFolderClick = () => {
    appState.hideSidebar();
  };
</script>

{#snippet folderRow(folder: Folder)}
  <li class="folder {appState.selectedFolder === folder.id ? 'selected' : ''}">
    <a href="?folder={encodeURIComponent(folder.id)}" class="title" onclick={handleFolderClick}>
      <span class="icon {folder.icon ? '' : 'default'}">{folder.icon || ''}</span>
      <span class="folder-name">{folder.title}</span>
    </a>
    <ul>
      {#each folder.children as child}
        {#if child.type === 'folder'}
          {@render folderRow(child as Folder)}
        {/if}
      {/each}
    </ul>
  </li>
{/snippet}

<nav class="folder-tree">
  <ul>
    {#each appState.bookmarks as item}
      {#if item.type === 'folder'}
        {@render folderRow(item as Folder)}
      {/if}
    {/each}
  </ul>
</nav>
