// src/components/SearchBar.tsx
import React, { useState, useContext, useEffect } from "react";
import { SearchContext } from "../context/SearchContext";
import { ThemeContext } from "../context/ThemeContext";

const SearchBar: React.FC = () => {
  const { searchQuery, setSearchQuery } = useContext(SearchContext)!;
  const [input, setInput] = useState(searchQuery);
  const { hideSidebar } = useContext(ThemeContext)!;
  const inputRef = React.useRef<HTMLInputElement>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
    setTimeout(() => {
      setSearchQuery(e.target.value);
    }, 1000);
  };

  const handleClear = () => {
    setInput("");
    setSearchQuery("");
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      hideSidebar();
    }
  };

  useEffect(() => {
    const handleGlobalKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "k") {
        inputRef.current?.focus();
        e.preventDefault();
      }
    };

    window.addEventListener("keydown", handleGlobalKeyDown);
  }, []);

  return (
    <div className="searchbar">
      <input
        ref={inputRef}
        type="text"
        placeholder="Search bookmarks..."
        value={input}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
      />
      {input && <button title="Clear" onClick={handleClear} />}
    </div>
  );
};

export default SearchBar;

// src/lib/components/SearchBar.svelte
<script lang="ts">
  import { getAppState } from '$lib/state.svelte';
  import { onMount } from 'svelte';
  
  const appState = getAppState();
  let inputElement: HTMLInputElement;

  let inputValue = $state(appState.searchQuery);
  let timeout: ReturnType<typeof setTimeout>;

  const handleChange = (e: Event) => {
    const value = (e.target as HTMLInputElement).value;
    inputValue = value;
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      appState.searchQuery = value;
    }, 1000);
  };

  const handleClear = () => {
    inputValue = '';
    appState.searchQuery = '';
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      appState.hideSidebar();
    }
  };

  onMount(() => {
    const handleGlobalKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        inputElement?.focus();
        e.preventDefault();
      }
    };
    window.addEventListener('keydown', handleGlobalKeyDown);
    return () => {
      window.removeEventListener('keydown', handleGlobalKeyDown);
    };
  });
</script>

<div class="searchbar">
  <input
    bind:this={inputElement}
    type="text"
    placeholder="Search bookmarks..."
    value={inputValue}
    oninput={handleChange}
    onkeydown={handleKeyDown}
  />
  {#if inputValue}
    <button title="Clear" aria-label="Clear Search" onclick={handleClear}></button>
  {/if}
</div>
